### ISSUE TITLE
BOARD=milkv-duo256m-lite not working

### ISSUE THREAD

**Issue by Spitzbube** [logicethos/Milk-V_Duo_Linux2SD#1]
It seems that the BOARD=milkv-duo256m-lite is no longer supported in https://github.com/milkv-duo/duo-buildroot-sdk/tree/develop/device.
But the adaption of the ENV to milkv-duo256m works.
Besides this the created image is even working on an LincheeRV Nano.  

Great job!

**Comment by 0xStuart** [comment]
Thanks, I have updated that.
